<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQkti6gl\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQkti6gl/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerQkti6gl.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerQkti6gl\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerQkti6gl\appDevDebugProjectContainer([
    'container.build_hash' => 'Qkti6gl',
    'container.build_id' => '4dec7d86',
    'container.build_time' => 1610450361,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQkti6gl');
